### ISSUE TITLE
Is git annex sync the equivalent of datalad push?

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/knowledge-base#50]
Origin: DataLad Matrix Chat Room 2023-05-03

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [x] Nature of the issue is understood
- [x] Inform OP about resolution

**Comment by jsheunis** [comment]
Communicated to user:

> The `datalad push` command internally uses `git push`, and `git annex copy` to push a dataset. AFAICT `git annex sync` only syncs git branches and not the annexed data.

Further information:

- https://git-annex.branchable.com/sync/
- https://git-annex.branchable.com/git-annex-sync/
- `git annex config --set annex.synccontent true` will also sync content
- `git annex sync` can pull and merge branches, `datalad push` does none of those. The relevant datalad command would be `datalad update`

**Comment by adswa** [comment]
Just as with #51, I do not think that enough is done to warrant closing this issue. The question is legitimate, and the answer in a chatroom is not persistent. In this specific case, users could read documentation and sourcecode to figure the answer out themselves. But as with other issues in this repo, a KBI with a persistent write-up would be the preferred way to close this issue, IMHO, so that future users are spared this extra work. We already went through the trouble of outlining this in the chat, making the information persistent is little additional work for us, improved UX for users, and faster future support duties if the question comes up again.
